on:
  push:
  pull_request_review_comment:
    types: [created]

jobs:
  echo-input:
    runs-on: ubuntu-latest
    # if: >
    #   github.event.name == 'push' ||
    #   (
    #     github.event.name == 'pull_request_review_comment' &&
    #     github.event.payload.user.login == 'okitan'
    #   )
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          script: await require('./script/push.js')({ github, context })
