on:
  push:
  pull_request_review_comment:
    types: [created]

jobs:
  echo-input:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request_review_comment'
      )
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ toJSON(github) }}"
      - uses: actions/github-script@v4
        with:
          script: await require('./script/push.js')({ github, context })
